= Azure Resume

== Frontend
Created some simple html and css for the visuals. The _script.js_ file is
sending a request to an Azure function and that Azure Function returns the
number of users that have accessed the webpage from cosmosdb.

[source, javascript]
----
// get counter paragraph element from dom
const doc_visitor_count = document.querySelector("#counter p");

// send a post request to Azure Function
fetch("https://austinsresumefunction.azurewebsites.net/api/httpexample", {
    method: "POST",
    headers: {
        "Accept": "application/json",
    }
}).then(
    // Get response and parse JSON data
    res => res.json()
).then(data => {
    // change html element's content to the `count` property of the response
    // data
    doc_visitor_count.innerHTML = data.count.toString()
})
----

== Backend

The Backend is just an Azure Function that uses Azure Cosmos DB output bindings
following the In-process model. The asynchronous function `HttpResponseMessage`
has some important parameters

=== `req` HttpResponseMessage parameter

[source, cs]
----
[HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
----

This parameter is used to respond to  a "get", or "post" requests. It uses
anonymous authorization level meaning that no API key is required to invoke the
function. `req` well contain

=== `counter` HttpResponseMessage parameter

[source, cs]
----
[CosmosDB(databaseName: "my-database", collectionName: "my-container", Id = "1",
                        PartitionKey = "1", 
                        ConnectionStringSetting = "CosmosDbConnectionString")]
                        Counter counter,
----

This parameter connected to cosmosdb using the database that has the name
"my-database", collection named "my-container", Id of 1 and PartitionKey
of 1. It will contain the output of this query in `counter`;

=== `updateCounter` HttpResponseMessage parameter

[source, cs]
----
[CosmosDB(databaseName: "my-database", collectionName: "my-container",
 Id = "1", PartitionKey = "1",
 ConnectionStringSetting = "CosmosDbConnectionString"
 )] out Counter updatedCounter,
----

This parameter also connects to cosmosdb using the specific values from the
attribute but it is used to send data back to the database.
